- lua/shine/core/shared/base_plugin.lua
- lua/shine/extensions/afkkick.lua
- lua/shine/extensions/chatbox/client.lua
- lua/shine/extensions/mapvote/server.lua
- lua/shine/extensions/mapvote/shared.lua
- lua/shine/extensions/pregame/server.lua
- lua/shine/extensions/pregame/shared.lua
- lua/shine/extensions/voterandom.lua
- lua/shine/lib/gui.lua
- sh_revote is gone, was a pointless command. sh_vote will just change the vote if used again.
- Pregame plugin now shows messages similar to the vanilla pregame while waiting for commanders.
- Fixed minor layout annoyance on the chatbox.
> More minor refactoring

- lua/ConfigFileUtility.lua
- lua/shine/core/client/adminmenu.lua
- lua/shine/core/client/votemenu_gui.lua
- lua/shine/core/server/commands.lua
- lua/shine/core/server/permissions.lua
- lua/shine/core/server/votemenu.lua
- lua/shine/core/shared/votemenu.lua
- lua/shine/extensions/basecommands/shared.lua
- lua/shine/extensions/voterandom.lua
- lua/shine/lib/gui.lua
- lua/shine/lib/gui/objects/button.lua
- lua/shine/lib/gui/objects/menu.lua
- lua/shine/lib/gui/objects/tabbedpanel.lua
- lua/shine/lib/gui/objects/textentry.lua
- lua/shine/lib/gui/skins/default.lua
- lua/shine/lib/utf8.lua
- Added option to account for standard deviation when sorting players.
- Made the UTF8 functions fail gracefully by falling back to the standard Lua string library if they encounter invalid UTF8.
- Made some minor improvements to the admin menu.
- Added "CanAlwaysTarget" flag for groups. If set, the group can always be targeted regardless of immunity.
- Added support for wildcards in string argument restrictions.
- Removed a pointless call to GetFileExists (io.open in read mode returns nil if the file doesn't exist) in the NS2 ConfigFileUtility code which was breaking Combat.
> Some script error fixes and minor improvements

- lua/shine/extensions/chatbox/client.lua
- lua/shine/lib/utf8.lua
There were some changes to the chatgui which "crash" the shine-chatbox in 275.
Diff of the given changes https://gist.github.com/GhoulofGSG9/93e622822374249f49de
Was asked by matso to open this request as currently it's not possible to play with build 275 at servers with shine.
Anyway just a warning: There might be a lot more gui changes that affect shine in build 275. Will try to write a detailed report once build 275 is in RC Mode ;)
> Resolved issue of the chatbox with build 275

- lua/shine/core/server/permissions.lua
- lua/shine/core/shared/chat.lua
- lua/shine/core/shared/extensions.lua
- lua/shine/extensions/chatbox/client.lua
- lua/shine/lib/gui.lua
- lua/shine/lib/gui/objects/textentry.lua
- lua/shine/lib/gui/skins/default.lua
- Text entry controls now support text selection and behave better in general.
- Updated chat values for 275.
- Use Shine:Print() for loading/reloading web users so it's logged properly.
- Add assertions for cyclic dependencies to help out anyone making plugins/GUI objects.
> Text entry improvements, minor fixes

- lua/shine/core/server/commands.lua
- lua/shine/extensions/basecommands/server.lua
- lua/shine/extensions/mapvote/server.lua
- lua/shine/extensions/mapvote/shared.lua
- lua/shine/extensions/voterandom.lua
- lua/shine/extensions/workshopupdater.lua
- lua/shine/lib/screentext/cl_screentext.lua
- Fixed error if a player has no skill data when sorting.
- The workshop updater plugin will no longer load if a workshop backup server is configured in ServerConfig.json.
- Fixed multiple small issues in the mapvote plugin.
> Fixes for small-ish bugs

- lua/shine/extensions/workshopupdater.lua
> Fix cancelling plugin load too late

- lua/ConfigFileUtility.lua
I'd imagine 275 will fix it, but why not fix it now.
> Fix bug in ConfigFileUtility

- lua/shine/lib/screentext/cl_screentext.lua
> Fix missing return value breaking old code

- lua/shine/core/server/permissions.lua
> Fix missing local after moving ConvertData

- lua/shine/core/server/commands.lua
- lua/shine/extensions/basecommands/server.lua
- lua/shine/extensions/mapvote/server.lua
- lua/shine/extensions/voterandom.lua
- lua/shine/lib/gui/objects/list.lua
- lua/shine/lib/gui/objects/panel.lua
- lua/shine/lib/gui/objects/scrollbar.lua
- Fixed votes to change map/shuffle teams having incorrect grammar at one vote left.
- Fixed the help text for commands showing the string version of the function if no help text is provided.
- Fixed a bug in the list/panel UI elements where they would not handle shrinking of the scrollbar correctly and potentially leave the view stuck.
> Minor bug fixes

- lua/shine/core/shared/hook.lua
Apparently, some weird Spark -> Lua/Lua -> Spark error means the old
method causes crashing on voting. Let's hope this doesn't.
> Redesign the NS2 vote system hook

- lua/shine/extensions/chatbox/client.lua
I didn't spend long enough looking at the rookie/commander tag stuff to realise it's possible to have both at once.
> Really fix message tags in the chatbox

- lua/shine/core/client/config.lua
- lua/shine/core/server/config.lua
- lua/shine/core/shared/logging.lua
- lua/shine/extensions/voterandom.lua
- lua/shine/lib/player.lua
- test/core/server/permissions.lua
- test/extensions/voterandom.lua
- test/test_init.lua
- Added pre and post EvenlySpreadTeams events.
- Refactored shuffling logic in the voterandom plugin to be more testable and to fix one small bug.
- Updated error reporting to send a list of enable mods for server-side errors.
- Disabled the local error log file by default.
> Shuffling refactor, EvenlySpreadTeams events, error logging changes

- lua/shine/extensions/voterandom.lua
and remove the notification about average skill. If people want or need
to know the values, they can use the command.
> Add command to view anonymous team stats

- lua/shine/core/client/votemenu_gui.lua
- lua/shine/extensions/chatbox/client.lua
Could use GUIScale, but I've already tweaked and tested these values so I'm not going to do that all again.
> Fix scaling between 1080p and 4K

- lua/shine/extensions/basecommands/server.lua
- lua/shine/extensions/pregame/server.lua
- lua/shine/extensions/voterandom.lua
- lua/shine/lib/datatables.lua
- lua/shine/lib/math.lua
- lua/shine/lib/table.lua
- readme.md
- test/extensions/voterandom.lua
- test/lib/math.lua
- test/test_init.lua
- Added "AllTalkLocal" option.
- Made `table.ChooseRandom` more sane.
- Improved test output and added test around `math.GenerateSequence`.
- Fixed randomly assigned players potentially making team counts uneven when they don't need to be.
> Local all talk and some minor fixes

- lua/shine/cl_init.lua
- lua/shine/extensions/chatbox/client.lua
- lua/shine/extensions/voterandom.lua
- lua/shine/lib/gui.lua
- lua/shine/lib/gui/objects/textentry.lua
- lua/shine/lib/player.lua
- lua/shine/lib/table.lua
- lua/shine/lib/utf8.lua
- test/lib/player.lua
- test/lib/table.lua
- test/lib/utf8.lua
- test/test_init.lua
- Text wrapping and cursor position finding are now faster.
- UTF8 handling is generally more sensible, any bad input is "fixed" rather than completely ignored.
- Fixed minor shuffle bugs, including balancing when aliens have one more player not being performed as intended.
> UTF8 optimisations, small shuffle fixes

- lua/shine/extensions/basecommands/server.lua
It's pointless, and not available at the time of loading anyway.
> Don't use an upvalue for PrintTableToConsole

- lua/shine/core/shared/base_plugin.lua
- lua/shine/extensions/chatbox/client.lua
- Fixed inheritance inheriting from the base before a parent plugin, which breaks expected behaviour.
- Fixed the chatbox erroring if you pressed up before pressing down when auto-completing.
> Small fixes for issues

- lua/shine/core/shared/base_plugin.lua
- lua/shine/core/shared/chat.lua
- lua/shine/extensions/afkkick.lua
- lua/shine/lib/datatables.lua
- lua/shine/lib/gui/objects/slider.lua
- lua/shine/lib/player.lua
- Fixed "inf", "nan" and hex values being considered numbers instead of names.
- Fixed small typo in the afk kick connection event.
> Small bug fixes

- lua/shine/extensions/afkkick.lua
Also added an extra hook for commanders so their time is reset when giving orders.
> Fix AFK plugin's "KickOnConnect" using wrong time units

- lua/shine/extensions/afkkick.lua
- lua/shine/extensions/ban/server.lua
- lua/shine/extensions/basecommands/server.lua
- lua/shine/extensions/namefilter.lua
- lua/shine/extensions/pingtracker/server.lua
- lua/shine/extensions/welcomemessages/server.lua
- lua/shine/extensions/workshopupdater/server.lua
- lua/shine/lib/player.lua
- lua/shine/lib/string.lua
Also accounted for `Gamerules:JoinTeam()` failing when sorting players onto teams better.
> Add reasons to all kicks

- lua/shine/core/shared/hook.lua
- lua/shine/extensions/ban/server.lua
- lua/shine/extensions/namefilter.lua
- lua/shine/extensions/reservedslots.lua
Also change the default move rate to be in line with build 295.
> Add disconnect reasons to CheckConnectionAllowed events

- lua/shine/extensions/afkkick.lua
Allow other plugins to react to changes in a player's AFK status.
( also move 0.25 to Config.KickTimeIsAFKThreshold so serverop controls IsAFK timing )
> Add AFKChanged hook

- locale/shine/extensions/pregame/csCS.json
Remove non-ascii characters from messages displayed with ascii-only
font.
> improve cs translation

- locale/shine/extensions/pregame/csCS.json
- lua/shine/core/client/adminmenu.lua
- lua/shine/core/shared/base_plugin/networking.lua
- lua/shine/extensions/basecommands/server.lua
- `sh_listplugins` can now be used by anyone.
- Czech translation improvements (thanks kparal).
- Network message receivers now catch and report errors.
- Fixed the admin menu having some text going outside the window.
- Changed some commands in the base commands plugin to no longer log/broadcast messages that should only be seen by the player running the command.
> Minor fixes/changes for base commands, text, error reporting

- lua/shine/core/server/permissions.lua
- lua/shine/core/shared/base_plugin/networking.lua
- lua/shine/core/shared/chat.lua
- lua/shine/extensions/basecommands/server.lua
- lua/shine/extensions/basecommands/shared.lua
- lua/shine/extensions/pregame/server.lua
- lua/shine/extensions/tournamentmode/server.lua
- lua/shine/extensions/voterandom/server.lua
- test/core/server/permissions.lua
- Updated to account for the new warm-up game state (thanks Ghoul).
- Fixed a rare script error in chat message handling.
> Build 302 fixes and minor error report changes

- lua/shine/extensions/voterandom/server.lua
Made sure only player who attempt to join a playing team get randomized into a team.
> Fixed that players couldn't join spectators after a shuffle.

- lua/shine/core/server/permissions.lua
- lua/shine/core/shared/hook.lua
- lua/shine/extensions/reservedslots.lua
- lua/shine/extensions/voterandom/server.lua
- test/extensions/reservedslots.lua
- test/test_init.lua
- Updated the reserved slot plugin to not block spectator slots.
- Updated the shuffle plugin to not shuffle players in spectator slots.
> Support spectator slots

- lua/shine/extensions/mapvote/server.lua
- lua/shine/extensions/voterandom/server.lua
- lua/shine/extensions/votesurrender/server.lua
- lua/shine/lib/math.lua
- lua/shine/lib/objects/votes.lua
- lua/shine/modules/sh_vote.lua
- test/extensions/voterandom/voterandom.lua
* Fixed `math.StandardDeviation` not returning the average when there are no entries in the provided table.
* Made votes that pass due to a client disconnecting delay the success for a tick to allow mods/vanilla code to react to the disconnect first.
> Fix a few minor script errors

- lua/shine/extensions/chatbox/client.lua
Data structure of GUIManager.scripts changes with build 328. Because the plugin allready hooks into the GUIChat class let's just set the plugin's GUIChat reference via the GUIChat's Un/Initialization methods.
> Update chatbox for ns2 build 328

- lua/shine/cl_init.lua
- lua/shine/core/shared/hook.lua
- lua/shine/extensions/afkkick/server.lua
- lua/shine/extensions/ban/client.lua
- lua/shine/extensions/mapvote/server.lua
- lua/shine/init.lua
- lua/shine/startup.lua
* Fixed alignment of page text entry.
* Fixed script error when moving players to the ready room at the end of the round when some players are bots.
> Fix minor bugs with moving players and the bans page

- locale/shine/extensions/chatbox/enGB.json
- lua/shine/core/client/config_gui.lua
- lua/shine/core/shared/extensions.lua
- lua/shine/core/shared/hook.lua
- lua/shine/extensions/chatbox/client.lua
- lua/shine/extensions/improvedchat/client.lua
- lua/shine/extensions/voterandom/server.lua
- lua/shine/lib/string.lua
- test/core/server/permissions.lua
- test/core/shared/hook.lua
- test/test_init.lua
* Fixed more scaling issues at resolutions other than 1920x1080.
* Added a button to open the config menu chat settings.
* Altered the settings scrollbar to be permanently visible.
* Fixed occasional script error when auto-completing commands/arguments.
* Fixed occasional script error when displaying a message due to the local player having no chat sound.
* Fixed potential script error when shuffling players with friend groups.
* Altered certain read-only hooks to ignore listener return values (using the new `Hook.Broadcast` function) and thus always call the event on all listeners.
> Bug fixes and improvements to chatbox

- lua/shine/extensions/improvedchat/server.lua
- lua/shine/extensions/mapvote/client.lua
- lua/shine/extensions/serverswitch/server.lua
- lua/shine/extensions/serverswitch/shared.lua
- lua/shine/lib/gui.lua
- lua/shine/lib/gui/base_control.lua
- lua/shine/lib/gui/objects/list.lua
- lua/shine/lib/gui/objects/listentry.lua
- lua/shine/lib/gui/objects/panel.lua
- lua/shine/lib/gui/objects/richtext.lua
- lua/shine/lib/gui/objects/slider.lua
- lua/shine/lib/gui/objects/textentry.lua
- lua/shine/lib/gui/objects/webpage.lua
- lua/shine/lib/gui/skins/default.lua
- lua/shine/lib/gui/skins/default_light.lua
* Empty chat tag text is now ignored.
* Fixed the map vote notification sometimes blocking mouse input (most noticeable when attempting to click the chatbox settings button).
* Fixed config validation preventing use of hostnames.
* Improved config validation to reject invalid IP address values.
* Hostnames can now be up to 63 bytes long (up from 15).
* Fixed mouse input being blocked in the main menu when an SGUI window is opened (such as the MOTD).
* TextEntry controls now handle the `Home` and `End` buttons as expected.
* Fixed text sometimes disappearing when clicking a slider's label to edit it.
> Minor bug fixes for UI elements and server switch

- lua/shine/core/server/logging.lua
- lua/shine/extensions/badges.lua
- lua/shine/lib/objects/map.lua
- test/extensions/badges.lua
- test/lib/objects/map.lua
* Improved performance of badge assignment by assigning badges lazily as users connect or to connected users on reload, rather than parsing the entire user data every time it reloads.
* Improved performance of saving the daily log file after startup.
> Improve performance of logging and badge assignment

- lua/shine/extensions/badges.lua
- lua/shine/extensions/mapvote/ui/map_vote_menu.lua
- lua/shine/lib/table.lua
- test/lib/table.lua
* Fixed regression in previous update that prevented forced badges from being assigned to members of the default group or reconnecting players.
* Fixed the current winning map(s) not being highlighted when opening the map vote menu after votes have been cast.
* Improved performance of JSON serialisation (most noticeable when saving large configuration files).
> Minor bug fixes and JSON serialisation performance improvements

- locale/shine/extensions/voterandom/enGB.json
- lua/shine/core/client/commands.lua
- lua/shine/core/client/config_gui.lua
- lua/shine/core/server/commands.lua
- lua/shine/core/server/logging.lua
- lua/shine/core/shared/commands.lua
- lua/shine/extensions/reservedslots.lua
- lua/shine/extensions/voterandom/client.lua
- lua/shine/extensions/voterandom/friend_groups.lua
- lua/shine/extensions/voterandom/shared.lua
- lua/shine/lib/gui/objects/checkbox.lua
- lua/shine/lib/gui/objects/radio.lua
- lua/shine/lib/gui/skins/default.lua
- lua/shine/lib/gui/skins/default_light.lua
- test/extensions/reservedslots.lua
* Altered the disconnect message when a player is rejected due to a reserved spectator slot to make it clearer that the slot was reserved, rather than the server being full.
* Added an option to automatically accept friend group requests from Steam friends (with the default being to accept them).
* Fixed console table output sometimes being mis-aligned.
* Command parameters now have their type validated when added to avoid being able to register invalid parameters.
* SGUI checkboxes/radio controls now have a disabled state.
* Client configuration settings can now alter the margin around their UI element by adding a `Margin` table.
> Minor improvements to various plugins

- lua/shine/extensions/adverts/server.lua
- lua/shine/extensions/chatbox/client.lua
- lua/shine/extensions/improvedchat/client.lua
- lua/shine/lib/gui/objects/textentry.lua
* Fixed a rare script error at startup.
* Fixed a few more issues with the upcoming build 335 game update.
> Fix more chat issues for build 335

- lua/shine/core/client/chat.lua
- lua/shine/extensions/improvedchat/client.lua
- lua/shine/extensions/votesurrender/server.lua
- lua/shine/lib/gui.lua
- test/extensions/votesurrender.lua
* Fixed chat positioning in build 336.
* Updated config field names to better reflect their units.
* Fixed a script error that occurred as a commander when notifications are visible.
> Update chat handling for build 336, fix minor issues

- lua/shine/core/client/config_gui.lua
- lua/shine/core/server/config.lua
- lua/shine/core/server/permissions.lua
- lua/shine/extensions/ban/server.lua
- lua/shine/extensions/mapvote/cycle.lua
- lua/shine/extensions/mapvote/map_data_repository.lua
- lua/shine/extensions/usermanagement.lua
- lua/shine/lib/external_apis.lua
- lua/shine/lib/gui/base_control.lua
- lua/shine/lib/gui/objects/button.lua
- lua/shine/lib/gui/objects/dropdown.lua
- lua/shine/lib/gui/objects/list.lua
- lua/shine/lib/query.lua
* Improved handling of vanilla ban data to ensure values have the expected type.
* Improved HTTP request error handling to provide a more informative reason for failed requests.
* Fixed dropdown menus getting stuck on the screen when closing the client config menu or chatbox with the escape button while a menu is open.
* SGUI controls can now observe changes to their effective visibility state by implementing the `OnEffectiveVisibilityChanged` method.
> Fix various bugs, improve HTTP error handling

- lua/shine/core/shared/extensions.lua
- lua/shine/core/shared/logging.lua
- lua/shine/extensions/mapvote/map_data_repository.lua
- lua/shine/lib/objects/comparator.lua
- lua/shine/lib/query.lua
- test/lib/objects/comparator.lua
* Fixed a rare client script error on startup.
* Updated the address used for various web APIs.
* Comparators now handle nil values, treating them as a lower value than any other value (ascending sorts them to the front, and descending sorts them to the back).
> Update API address, fix minor bugs

- lua/shine/core/shared/hook.lua
- lua/shine/lib/debug.lua
- lua/shine/lib/table.lua
- test/lib/debug.lua
* Updated usage of the `debug` library to account for upcoming Lua sandbox changes in the next game update.
> Fix debug library usage under new sandbox

- lua/shine/core/shared/hook.lua
- lua/shine/extensions/afkkick/server.lua
- lua/shine/extensions/ban/server.lua
- lua/shine/extensions/basecommands/server.lua
- lua/shine/extensions/namefilter.lua
- lua/shine/extensions/pingtracker/server.lua
- lua/shine/extensions/voterandom/server.lua
- lua/shine/extensions/welcomemessages/server.lua
- lua/shine/lib/player.lua
- test/extensions/voterandom/voterandom.lua
* Fixed `sh_kick` crashing the server if used on bots.
Fixes #897
> Mitigate engine crash on Server.DisconnectClient
