lua/shine/core/shared/extensions.lua
The basecommands plugin was blocking the afk kick plugin from receiving the voice chat event.
=> Fix AFK tracking not removing AFK time in pregame

lua/shine/core/shared/chat.lua
These two fields get used with 275 for indicating if sender is commander and if sender is rookie. As AddChatMessage() is only used for shine message we set both those fields to false. Works also with 274
=> Fixed that AddChatMessage() did not work with 275

lua/shine/core/client/commands.lua, lua/shine/core/server/commands.lua, lua/shine/core/shared/commands.lua, lua/shine/core/shared/hook.lua, lua/shine/extensions/ban/server.lua, lua/shine/extensions/ban/shared.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/commbans/server.lua, lua/shine/extensions/funcommands/server.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/serverswitch/server.lua, lua/shine/extensions/tournamentmode/server.lua, lua/shine/extensions/unstuck.lua, lua/shine/lib/debug.lua, lua/shine/lib/gui.lua, lua/shine/lib/gui/objects/textentry.lua, lua/shine/lib/string.lua
- Added sh_customvote command, calls a vote with the given question.
- Commands that use time values are now easier to work with.
- For ban commands, you can now use short form strings, for example `1w` represents 1 week, `2h5m` represents 2 hours and 5 minutes.
- For the mapvote plugin's round time commands, you can even use full sentence times, such as `1 week` or `2 hours and 5 minutes`.
- The old behaviour of entering time in minutes as a number is still supported.
- Added a label under the duration text box in the admin menu when banning through the bans/commbans plugin that displays what the duration you are entering is being interpreted as. This should help avoid any confusion/unintended durations.
- The text entry control now supports selecting whole words by double clicking on …
=> Custom votes, easier defining of time

lua/shine/core/client/adminmenu.lua, lua/shine/core/client/votemenu_gui.lua, lua/shine/core/shared/webpage.lua, lua/shine/extensions/ban/shared.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/lib/gui.lua, lua/shine/lib/gui/objects/label.lua, lua/shine/lib/gui/objects/list.lua, lua/shine/lib/gui/objects/listheader.lua, lua/shine/lib/gui/objects/panel.lua, lua/shine/lib/gui/objects/scrollbar.lua, lua/shine/lib/gui/objects/tooltip.lua, lua/shine/lib/screentext/cl_screentext.lua
- Fixed map vote messages showing "blah revoted for blah map" when they're choosing the same map twice or more. It now shows an error message to the player instead, telling them they've already voted for it.
- Fixed popup menus in the commands tab of the admin menu requiring two clicks to re-open if you clicked elsewhere in the menu to close them.
- Lists now highlight the header that they are sorting by.
- List scrolling with the mouse wheel now scrolls faster.
- Lists in the admin menu (with the exception of the commands tab's player list) now remember which rows were selected when switching away and back.
- Fixed the unload plugin button in the plugins tab of the admin menu being usable on already unloaded plugins.
- The plugins tab no longer populates if you do not have permission to …
=> Multiple UI improvements

lua/shine/core/client/votemenu.lua, lua/shine/core/shared/base_plugin.lua, lua/shine/extensions/adverts.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/mapvote/shared.lua, lua/shine/extensions/pregame/server.lua, lua/shine/extensions/pregame/shared.lua, lua/shine/extensions/tournamentmode/server.lua, lua/shine/lib/screentext/cl_screentext.lua, lua/shine/lib/screentext/sh_screentext.lua, lua/shine/lib/screentext/sv_screentext.lua
- Fixed the ServerConfig.json settings it changes not being reset at map change thus potentially leaving them altered if it is then disabled next map.
- You can now use the !ready command to toggle between ready and unready.
- The ready state of teams when everyone is required to be ready should be notified more clearly now.
- Refactored everything into its own table under `Shine.ScreenText` and made server and client usage roughly identical.
- On the client, creating a new screen text element returns a usable object that can be used to remove/change the text.
- The old functions are still present but deprecated and will be removed in the near future.
- Fixed plugins inheriting the state of their parent plugin.
=> Screen text refactor, bug fixes to tournament mode and plugin inheritance

lua/shine/extensions/votesurrender/server.lua
Often player vote to surrender even though their team still has multiple bases (techpoints/hives/CCs). 
To stop this behavior i added a option which allow server operators to disallow to surrender with multiple bases.
Also removed GetTeamPlayers() as it is not used at all.
=> VoteSurrender: Option to disallow voting with multiple team bases

lua/shine/core/shared/hook.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/workshopupdater.lua
Was adding currentMap = currentMap or Shared.GetMapName() really that
hard to do to keep backwards compatibility?
=> Fix map cycling

lua/shine/extensions/ban/server.lua, lua/shine/extensions/commbans/shared.lua
The CheckConnectionAllowed is triggered immediately after the first "handshake" packets have been exchanged between client and server. The ClientConnect event on the other hand is called when the client is almost done with loading.
So moving the check should save server bandwidth and avoids that banned clients block the "clients connecting" queue.
=> [Suggestion] [Ban] Use the CheckConnectionAllowed event to verify clients

lua/shine/extensions/voterandom.lua, test/extensions/voterandom.lua
Before it would get stuck trying to improve the standard deviation and fail, thus stopping at a (often bad) point.
This change allows it to reduce the average while increasing the standard deviation slightly which gets it out of its stuck point and produces much better team compositions at the end.
=> Alter the shuffling algorithm's approach to standard deviation balancing

lua/shine/extensions/voterandom.lua, test/extensions/voterandom.lua
- Fixed that swaps that lowered the difference between team's standard deviations were being discarded for those that increase it.
- Made the tolerance value configurable.
=> Further tweaks to shuffling

lua/shine/extensions/ban/server.lua
Often player wonder about the reason of a ban when they see the given message. 
Therefor it would make things more simple to just include the ban reason in the message.
=> Inform the public about the ban reason when sh_ban is used.

lua/shine/extensions/voterandom.lua
=> Better account for stored stat values

lua/shine/extensions/mapvote/cycle.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/extensions/voterandom.lua, test/extensions/mapvote.lua, test/extensions/voterandom.lua, test/test_init.lua
- Map vote plugin can now track maps played and stop maps going over a percentage of the total played.
- Shuffle plugin now correctly resets the round block time after a reset vote.
=> Added percentage played tracking for mapvote, fixed shuffle block time

lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/lib/gui.lua, lua/shine/lib/gui/objects/panel.lua
- Fixed the case where no channel identifier is passed through the `CanPlayerHearPlayer` event (such as commander alerts).
- The chatbox now wraps in the same manner as the vanilla chat display.
=> Fix commander alerts and alter chatbox text wrapping

lua/shine/extensions/chatbox/client.lua
But only if the new max height is less than the existing max. Otherwise it brings back that 1-frame skip on scrolling.
=> Re-add the max height adjustment

lua/shine/core/client/votemenu_gui.lua, lua/shine/core/server/votemenu.lua, lua/shine/core/shared/votemenu.lua, lua/shine/extensions/afkkick.lua
- Added experimental option to kick the longest AFK player when the server's full and a new player tries to join. Have no way to test it as bots don't count as real clients.
- Renamed the RTV button to "Map Vote" to avoid confusion around what RTV means.
- Fixed a layout glitch when the admin menu button is added to the vote menu for the first time.
=> Kick on connection for AFK kick plugin, rename RTV

lua/shine/extensions/chatbox/client.lua
When changing resolution, the control may have been destroyed.
=> Add validity check

lua/shine/core/client/votemenu_gui.lua, lua/shine/core/server/logging.lua, lua/shine/extensions/mapvote/shared.lua, lua/shine/extensions/voterandom.lua, lua/shine/lib/gui/objects/image.lua
- The shuffle plugin's forcing of players onto teams when enforcing teams no longer passes the force argument.
- Fixed colour notifications not actually enforcing the message size limit.
- Added small previews of maps when hovering over their button in the vote menu. This only works for maps whose preview is currently mounted, so custom maps will not have a preview unless they're always mounted.
=> Add map previews in the vote menu, other small fixes

lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua, lua/shine/lib/map.lua, lua/shine/lib/timer.lua, test/lib/map.lua
- Added `HighlightTeamSwaps` option to the "voterandom" plugin. When a player joins a new team, their entry on the scoreboard will be translucent and slowly fade in for 10 seconds after the change of team.
- Fixed the `Map` object not removing keys mapped to `false`.
- Fixed timer tracebacks showing the error handler function.
=> Add team swap highlighting, and small cleanup/bug fixes

lua/shine/extensions/voterandom/shared.lua
Apparently rows might not have a client index, and scoreboard entries may not exist for them...
=> Add some nil checks

lua/shine/extensions/afkkick.lua, lua/shine/extensions/badges.lua, test/extensions/afkkick.lua, test/extensions/badges.lua, test/test_init.lua
Lets you set a globally defined set of rows, then all groups will use that to determine which rows to place their badges in.
=> Add master badge table and cleanup badges plugin

lua/shine/extensions/badges.lua
Forgot to account for the group lookup table argument.
=> Fix small mistake in assigning group badges

lua/shine/extensions/badges.lua, lua/shine/extensions/voterandom/shared.lua, lua/shine/lib/map.lua, test/extensions/badges.lua, test/lib/map.lua
- Specifying badges in multiple rows in the master table will now put them in those multiple rows when given in a group's `Badges` array.
- Team entries in the scoreboard now oscillate between translucent and opaque after a player swaps teams, rather than just fading in.
=> Make the master badge table a multimap, oscillate swapped team player entries

lua/shine/cl_init.lua, lua/shine/core/server/commands.lua, lua/shine/core/server/config.lua, lua/shine/extensions/adverts.lua, lua/shine/extensions/afkkick.lua, lua/shine/extensions/ban/server.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/commbans/shared.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua, lua/shine/init.lua, lua/shine/lib/external_apis.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/objects/checkbox.lua, lua/shine/lib/gui/objects/slider.lua, lua/shine/lib/gui/objects/textentry.lua, lua/shine/lib/map.lua, lua/shine/lib/math.lua, lua/shine/lib/player.lua, lua/shine/lib/query.lua, lua/shine/lib/queue.lua, lua/shine/lib/table.lua, lua/shine/lib/utf8.lua, test/lib/math.lua, test/lib/queue.lua, test/lib/table.lua, test/test_init.lua
- Added an easy to use external API system that allows for hitting web APIs and automatically handling result caching, request parameter conversion and keeping concurrent requests in check.
- The bans plugin can now use this to check for family sharing status on connecting players, and kick them out of they have the game shared to them by a banned account.
- The shuffling plugin can now display the standard deviation of player "skill" level on the scoreboard.
- The adverts plugin can now display messages in a random order rather than in sequence.
=> External API support, and some feature requests/additions

locale/shine/extensions/basecommands/enGB.json, lua/shine/core/server/commands.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/mapvote/shared.lua, lua/shine/extensions/tournamentmode/server.lua, lua/shine/lib/debug.lua, test/lib/debug.lua
- Fixed a script error in the map vote plugin when a vote for the next map failed.
- Fixed a script error when clicking the gag button in the admin menu.
- Fixed the "Plugins" and "Maps" tab names not being translatable strings.
- The tournament mode ready and unready commands no longer require a ! or /.
=> Fix minor translation issues

lua/shine/core/shared/base_plugin.lua, lua/shine/extensions/voterandom/server.lua
It now throws an error indicating the attempted name, and the plugin responsible.
=> Fix plugins trying to send unregistered network messages

lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/extensions/voterandom/local_stats.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/objects/panel.lua
- Fixed the chatbox layout breaking when opening without a new message.
- Fixed a script error when attempting to vote for shuffled teams when the map is cycling.
- Fixed a script error in the local stats functionality of the shuffle plugin when a player disconnected before they had any playtime set.
=> Small bug fixes for the chatbox, local stats and translations

lua/shine/extensions/basecommands/server.lua
tick rate and move rate are rather independent from each other:
The move rate sets how often per second the clients are suppose to send a move update to the server.
The tick rate set how often per second the server runs it's update tick (includes the Lua VM update tick etc).
However there is no reason to let the clients send more move packets than the server is able to process.
Also the server should not send more world updates to the clients than it has possible data avaible from the clients move update packages.
=> Corrected network setting checks.

lua/shine/extensions/voterandom/team_balance.lua
If a call to the event changed the TeamMembers table, these values need re-computing.
=> Make sure that TeamSkills reflects the correct values

lua/shine/extensions/basecommands/server.lua
The move rate has been decreased to 26 with build 295 to decrease the overall load of the servers.
=> Changed the default moverate to 26 as done in build 295

lua/shine/extensions/votesurrender/server.lua
Build 298 added a new animation sequence that shows how the surrender teams bases blow up. 
Ns2 detects if a team conceded or not via a flag that get set by the concede votes success function. The surrender extension however never set given flag and therefor the sequence gets always skipped. I fixed that.
I also added a configuration setting for those server operators who want to skip the sequence just in case.
=> [Surrender] Play new concede in-game sequence

lua/shine/core/shared/extensions.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/afkkick/shared.lua, lua/shine/extensions/chatbox/chatline.lua, lua/shine/extensions/votesurrender/server.lua
- Added `NotifyOnWarn` option to the AFK kick plugin. Sets whether players should have their taskbar icon for NS2 flashed, and a sound played when they are warned for being AFK.
- Added `MovementDelaySeconds` option to the AFK kick plugin. Sets the number of seconds to wait after warning a player before performing a move action.
- Fixed some issues in the AFK plugin that made it less friendly to inheritance than intended.
- Fixed surrender votes not triggering the concede sequence (thanks Ghoul, even though your fix used the wrong team!).
- Fixed the chatbox not properly word wrapping messages that go beyond 2 lines, or that are added while it is closed.
=> AFK notification and movement delay, bug fixes, 298 update fix for concede

lua/shine/extensions/afkkick/server.lua
Always use time since last move, and check for whether the player is still warned, rather than the IsAFK flag.
=> Fix somewhat inconsistent movement/warn time behaviour

lua/shine/extensions/basecommands/server.lua
I would like to make the listplugins public for two reasons:
- It potentially allows me as developer to reproduce issues with my extensions / the game without contacting given server operator.
- It creates a certain degree of transparency for the users as they can now check what's running at the server. _In the past there have been server extensions granting operators in-game advantages which were directly uploaded to the server._
=> Allow everyone to use sh_listplugins

lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/pregame/server.lua, lua/shine/extensions/tournamentmode/server.lua, lua/shine/extensions/voterandom/server.lua
Build 302 adds a new `WarmUp` gamestate to the ns2 gamerules. The gamerules will switch into the `WarmUp` gamemode from `NotStarted` if the sum of players in the marine and alien team is below 12.
It will switch from `WarmUp` to `NotStarted if the same sum of players is equal or greater 12.
I adjusted all game state checks of shine to cover up for this change and also replaced all static numeric values for game states with reference to the `kGameState` table to make Shine compatible to future changes and mods that may define own game states as well (haven't seen one doing that yet though).
=> WarmUp game state of Build 302

locale/shine/extensions/pregame/enGB.json, lua/shine/core/shared/base_plugin/config.lua, lua/shine/extensions/pregame/server.lua, lua/shine/extensions/pregame/shared.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/extensions/votesurrender/server.lua, lua/shine/extensions/welcomemessages/server.lua, lua/shine/lib/table.lua, test/lib/table.lua
- Fixed bots being counted towards votes in the vote surrender plugin.
- Defaulted showing connection messages for bots to disabled.
- Added a 4th mode to the pregame plugin, which waits for a minimum team player count before allowing the game to start with 2 commanders.
- Renamed the mode option in the pregame plugin from `RequireComs` to `Mode`, and made the scale from 1 - 4 for each mode described on the wiki page. This will be automatically changed for you.
- Prevented the warmup bots from interfering with team shuffling. Use the new `ApplyToBots` setting to allow them to be shuffled (defaults to false, which removes them on a shuffle).
=> Various fixes to account for bots + new pregame mode

locale/shine/extensions/mapvote/enGB.json, lua/shine/core/shared/hotfix.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/extensions/pregame/server.lua
* Added `MaxNominationsPerPlayer` option to the mapvote plugin. Sets the maximum number of nominations a single player is allowed to make per vote.
* Added a hotfix to fix the commander bot code breaking team swapping.
=> Add option to limit nominations per player, small hotfix

lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua
- No longer move commanders to the ready room if they are AFK and `IgnoreCommanders` is true.
- Fix standard deviation not being correct on the scoreboard due to a logic flaw.
=> Fix small issues in the shuffle plugin

lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua, lua/shine/lib/gui/objects/webpage.lua, lua/shine/lib/table.lua
- Fixed players being blocked from entering spectate when team enforcing is enabled after a shuffle vote.
- Fixed a script error in the shuffle plugin when "AlwaysEnabled" mode is true.
- Fixed a script error in the base commands plugin when toggling local all-talk.
- Web components can now run Javascript and watch for Javascript alerts.
- Changed `table.Empty` to just be an alias to LuaJIT 2.1's `table.clear`.
=> Small bug fixes and minor feature changes

locale/shine/extensions/basecommands/enGB.json, lua/shine/core/client/adminmenu.lua, lua/shine/core/shared/extensions.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/pregame/server.lua, lua/shine/extensions/tournamentmode/server.lua, lua/shine/extensions/voterandom/local_stats.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/votesurrender/server.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/objects/menu.lua, lua/shine/lib/gui/objects/textentry.lua, lua/shine/lib/gui/skin_manager.lua, lua/shine/lib/gui/skins/default.lua
* Fixed a script error when `Player:GetMarinePlayTime()` or `Player:GetAlienPlayTime()` return `nil`.
* Fixed escape not closing command menus in the admin menu.
* Added a text entry for a custom kick reason to the kick command's menu.
* SGUI components now have the concept of styling states, allowing skins to define different properties for different states. Currently on `TextEntry` controls use this, and they have a single non-standard state called `Focus`.
* Made move detection more forgiving for spectators, and added the `LenientModeForSpectators` option to make AFK time reset to 0 when spectators move.
* Plugins can now define either a whitelist (`EnabledGamemodes`) or blacklist (`DisabledGamemodes`) of gamemodes and they will be automatically disabled when the current gamemode does …
=> UI improvements, AFK lenient mode, gamemode detection for plugins

lua/shine/extensions/badges.lua, lua/shine/extensions/voterandom/local_stats.lua
* Fixed script error due to badge functionality throwing an error when a badge is missing.
* Fixed a script error in vote shuffle's local stats recording when the game ends in a draw.
=> Small script error fixes for badges and local stats

lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/afkkick/shared.lua, lua/shine/extensions/voterandom/server.lua
- Clients in the Steam overlay are now always considered AFK.
- Fixed shuffling teams not kicking bots correctly.
=> Check for Steam overlay in AFK kick, and fix kicking bots

lua/shine/core/shared/base_plugin/config.lua, lua/shine/core/shared/config.lua, lua/shine/extensions/mapvote/cycle.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/extensions/namefilter.lua, lua/shine/lib/objects/set.lua, lua/shine/lib/objects/stream.lua, lua/shine/lib/objects/version.lua, lua/shine/lib/table.lua, test/extensions/mapvote.lua, test/lib/objects/set.lua, test/lib/objects/version.lua, test/lib/table.lua
- Configuration format for `ExcludeLastMaps` is now an object with `Min` and `Max` fields. `Min` determines the absolute minimum previous maps that must be removed from the choices, `Max` is an optional upper limit on the number to remove. Without an upper limit, the maximum will be the number of maps that can be removed that still allows for`MaxOptions` number of choices available.
- Default `VoteLength` is now 1 minute.
- JSON output will now alphabetically sort its keys.
- Added `Set` and `VersionHolder` objects.
- Improved `SortedPairs` to be able to handle any key type, regardless of whether they are comparable or not.
- Added new configuration migration system.
- Plugins can define `ConfigMigrationSteps` as a list of steps to apply to config files when their `__Version` value is …
=> Improve mapvote's previous map exclusions

lua/shine/core/shared/extensions.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/votesurrender/server.lua, lua/shine/lib/objects/map.lua, lua/shine/lib/objects/stream.lua, lua/shine/modules/vote.lua, test/extensions/mapvote.lua
- Fixed nominations not always being added to the final vote list.
- AFK players can now be excluded from all votes, both Shine's and the vanilla votes.
=> Fix nomination problems and allow excluding AFK players from votes

locale/shine/extensions/afkkick/enGB.json, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/afkkick/shared.lua, lua/shine/extensions/mapvote/cycle.lua, lua/shine/extensions/mapvote/voting.lua
- Fixed maps not respecting min/max/percent values.
- Changed the AFK warning when "KickOnConnect" is enabled to indicate that the player may be kicked when a new player joins.
=> Fix map options not being respected, and fix AFK warning with KickOnConnect

lua/shine/core/shared/hook.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/pregame/server.lua, lua/shine/lib/datatables.lua, lua/shine/lib/screentext/sh_screentext.lua, lua/shine/lib/screentext/sv_screentext.lua
- Fixed the all-talk message not behaving quite correctly in some cases.
- Fixed being able to use string formatting in csay messages.
- Replaced behaviour added in build 314 to fix all talk being disabled when the warm up mode ends (but only when using the `pregame` plugin).
- Fixed datatable change listeners not receiving the old value.
=> Update to account for NS2 build 314

lua/shine/extensions/chatbox/chatline.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/lib/objects.lua, lua/shine/lib/objects/logger.lua, lua/shine/modules/logger.lua, test/extensions/voterandom/voterandom.lua, test/lib/objects/logger.lua
- Added new, more fine grained logging for plugins. Any plugin can add this functionality by including the `logger` module.
- The shuffle plugin uses this logging functionality to log shuffle information before and after at the debug level.
- Fixed the chatbox not considering the position of the message label when word wrapping.
=> Add extra logging for shuffles, and fix chatbox wrapping

lua/shine/extensions/voterandom/team_optimiser.lua
When team counts were uneven, the swapping logic would always assume the larger team was team 1, rather than properly accounting for it, which would lead to random swaps including potentially commanders.
=> Fix not always swapping the right players

lua/shine/core/server/permissions.lua, lua/shine/extensions/ban/server.lua, test/core/server/permissions.lua, test/lib/table.lua
- Added `BanSharerOnSharedBan` option to the bans plugin. When enabled, banning a player that is playing the game through family sharing will also ban the account that is sharing the game to them.
- User groups set to be whitelists can now deny commands that are allowed by default.
=> Improve bans and group definitions

lua/shine/core/shared/hook.lua
`StartVote` is now a global, so we don't have to do awkward upvalue searching and re-registering network messages anymore.
=> Update NS2 vote hook to account for changes

locale/shine/extensions/workshopupdater/zhCN.json, lua/shine/core/client/adminmenu.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/namefilter.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/votesurrender/server.lua, test/extensions/votesurrender.lua
- The amount of time before a player is considered AFK when shuffling is now controlled by the `VoteSettings.AFKTimeInSeconds` option.
- Players can now be persistently gagged using `sh_gagid`/`sh_ungagid`.
- Players can now be persistently renamed with the name filter plugin using `sh_renameid`/`sh_unrenameid`.
- New options for surrender votes:
- `PercentNeededInEarlyGame` - When non-zero, sets the percentage of votes needed to surrender during the `VoteDelay` duration after a round start.
- `LastCommandStructureMinHealthPercent` - When non-zero, sets the percentage of health required on the last command structure to allow a surrender vote.
- Small Chinese translation fix (thanks axamdy).
=> Add persistent gagging/renames, more configuration options

locale/shine/extensions/afkkick/fiFI.json, lua/shine/extensions/ban/server.lua, lua/shine/extensions/commbans/server.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/lib/query.lua
- Bots are now prevented from re-joining until the end of a round after a shuffle vote has passed and `ApplyToBots` is set to false.
- Added Finnish translations for the afkkick plugin (thanks MisterOizo!)
- Improved logging behaviour in the bans plugin.
- Fixed the default value for `MaxAttempts` not applying correctly in `Shine.HTTPRequestWithRetry` when performing a `GET` request.
=> Fix bot behaviour in shuffle votes, other minor improvements

locale/shine/extensions/voterandom/enGB.json, lua/shine/core/client/config_gui.lua, lua/shine/core/server/commands.lua, lua/shine/core/shared/base_plugin.lua, lua/shine/core/shared/commands.lua, lua/shine/core/shared/config.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/chatbox/chatline.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/lib/gui/objects/checkbox.lua, lua/shine/lib/objects/map.lua, test/extensions/afkkick.lua, test/extensions/voterandom/voterandom.lua, test/lib/objects/map.lua, test/test_init.lua
- Team preferences can now be explicitly specified by players.
- When shuffling, a history of previous rounds indicating which players got to play the team they prefer is used to determine an overall score for how satisfied players are with their teams. If there are more players unhappy than happy, the final teams will be swapped entirely (i.e. marine becomes alien and vice-versa).
- Player AFK state is now always tracked, regardless of player count/round state. However, no action will be taken until the minimum player count/correct round state is reached.
- When the minimum player count/correct round state is reached, any player that has been AFK for greater than the warn/kick time will be warned/kicked immediately, rather than starting from 0 AFK time.
=> Make shuffle account for team preferences better, improve AFK tracking

lua/shine/extensions/voterandom/team_balance.lua
Avoid attempting to satisfy team preferences using historic happiness if commanders must be ignored.
=> Fix swapping commanders when total happiness is negative

lua/shine/core/client/votemenu_gui.lua, lua/shine/core/server/commands.lua, lua/shine/core/server/config.lua, lua/shine/core/shared/base_plugin/config.lua, lua/shine/core/shared/config.lua, lua/shine/core/shared/extensions.lua, lua/shine/core/shared/hook.lua, lua/shine/extensions/adverts.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/mapvote/shared.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/lib/debug.lua, lua/shine/lib/gui/objects/textentry.lua, lua/shine/lib/locale.lua, lua/shine/lib/objects.lua, lua/shine/lib/objects/stream.lua, lua/shine/lib/player.lua, lua/shine/lib/string.lua, lua/shine/lib/table.lua, lua/shine/modules/sh_vote.lua, test/core/shared/config.lua, test/extensions/adverts.lua, test/extensions/voterandom/voterandom.lua, test/lib/objects.lua, test/lib/string.lua, test/lib/table.lua, test/test_init.lua
* Adverts can now use templates to avoid repeating colours in messages.
* Adverts can now have a coloured prefix.
* Adverts can now be triggered on certain events, such as a round starting, as well as having a cycle.
* Adverts may be filtered by map/game state.
* When voting, buttons will show a tick on the button if you have already voted.
* The "Map Vote" button now displays a counter for the current number of votes to change the map.
* Fixed web configs not properly validating/migrating data.
* Added a recursive config check option for plugins, which checks all values in the default config except arrays and explicitly ignored tables using `Shine.IgnoreWhenChecking()`.
* Added `OnWebConfigReloaded` event for plugins.
* Improved the output format of configs when they are updated to make …
=> Improve vote menu, adverts plugin, config loading, web configs

locale/shine/extensions/unstuck/enGB.json, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/unstuck/server.lua, lua/shine/extensions/unstuck/shared.lua, test/extensions/afkkick.lua
* Time resetting behaviour can now be configured to one of 3 modes:
* `STRICT` - the existing mode, where time is only reduced with activity, not reset.
* `LENIENT_FOR_SPECTATORS` - equivalent to the old `LenientModeForSpectators` option, resets time for spectator activity, but still applies strict tracking to non-spectators.
* `LENIENT` - resets time for any player activity.
* The plugin will no longer unstick players that are trapped in bone walls.
* Added the `DelayBeforeMovingInSeconds` option, which allows for enforcing a delay between a player using the unstuck command and them being moved. If the player moves between this delay they will not be unstuck.
=> Improve AFK Kick config and unstuck behaviour

lua/shine/core/server/permissions.lua, lua/shine/core/shared/commands.lua, lua/shine/core/shared/hook.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/extensions/reservedslots.lua, lua/shine/lib/datatables.lua, test/extensions/reservedslots.lua
* Added new `SlotType` option. Can be either:
* `PLAYABLE` - the existing behaviour.
* `ALL` - treats all slots as a single max player limit, including spectator slots. This allows for reserving spectator slots.
* The end of map vote now blocks vanilla votes that would interfere or not function correctly while it is ongoing.
* Changed the error message when attempting to vote kick a player that has a higher immunity to state they cannot be targeted.
* Fixed a few issues with datatables.
=> Reserved slot, vanilla vote control and datatable improvements

locale/shine/extensions/mapvote/enGB.json, locale/shine/extensions/voterandom/enGB.json, lua/shine/core/client/config_gui.lua, lua/shine/core/client/votemenu_gui.lua, lua/shine/core/shared/config.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/mapvote/shared.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/extensions/voterandom/team_optimiser.lua, lua/shine/extensions/welcomemessages/server.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/objects/slider.lua, lua/shine/lib/gui/objects/tooltip.lua, lua/shine/lib/gui/skins/default.lua, lua/shine/modules/sh_vote.lua, test/extensions/voterandom/voterandom.lua
* Checking the Steam overlay can now be disabled using the config option `CheckSteamOverlay = false`.
* Opening the chatbox in team chat will now change the background colour slightly to reflect the team you are on. This should help make it clearer when it has been opened in team chat mode vs. global chat.
* The map vote menu may now be opened automatically for players when a map vote starts using the config option `ForceMenuOpenOnMapVote = true`.
* The menu will not open if a game is in progress or about to start.
* Clients may override this behaviour in the client config menu or using the `sh_mapvote_onvote` command in the console.
* Implemented an improved team optimisation pass that produces much more balanced teams compared to the old method in most cases.
* The optimisation process …
=> Improvements to AFK kick, chatbox, map vote, shuffle and welcome messages

lua/shine/core/shared/base_plugin/networking.lua, lua/shine/core/shared/extensions.lua, lua/shine/extensions/mapvote/shared.lua, lua/shine/lib/debug.lua
* Fixed plugins having their network receivers called when they are not enabled.
* Fixed plugin enabled state becoming inconsistent if failing to load after having previously loaded successfully.
* Errors in config loading and initialisation are now reported properly.
* Errors in `OnFirstThink` called by the initialisation process no longer prevent plugins from being enabled.
* The network message telling clients which shared plugins are enabled is now sent before server-side plugins can execute the `ClientConfirmConnect` event.
* Error handlers now return the error they handled to allow using the second return value of `xpcall`.
=> Fix minor plugin initialisation bugs

lua/shine/core/client/adminmenu.lua, lua/shine/core/client/config_gui.lua, lua/shine/core/client/votemenu_gui.lua, lua/shine/core/shared/hook.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/lib/gui/objects/tabbedpanel.lua
* Fixed edge cases that would result in the cursor disappearing when becoming a commander if menus were open at the time of entry.
* Fixed edge cases where menus would remain on the screen without a mouse cursor when leaving a command structure.
=> Fix mouse cursor disappearing and menus being left on screen

lua/shine/core/client/config_gui.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/chatbox/chatline.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/extensions/votesurrender/server.lua, lua/shine/lib/gui.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/layout/types/directional.lua, lua/shine/lib/gui/layout/types/horizontal.lua, lua/shine/lib/gui/layout/types/vertical.lua, lua/shine/lib/gui/objects/panel.lua, lua/shine/lib/gui/objects/scrollbar.lua, lua/shine/lib/math.lua, lua/shine/lib/objects/votes.lua, test/extensions/voterandom/voterandom.lua
* Fixed text potentially wrapping badly on lower resolutions.
* Fixed the history always scrolling to the bottom when opened, regardless of previous scroll state.
* Fixed changing the size of the chatbox always re-opening it in global chat mode regardless of the previous mode.
* Improved automatic team assignment logic when teams are blocked to better determine which team a new player should be placed on.
* Votes will now pass when a player leaving causes the total required votes to equal the total votes cast, rather than requiring another vote.
=> Fix minor chatbox and vote bugs, improve shuffle auto-assignment

locale/shine/extensions/voterandom/enGB.json, lua/shine/extensions/ban/server.lua, lua/shine/extensions/ban/shared.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/mapvote/cycle.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/extensions/voterandom/team_optimiser.lua, test/extensions/voterandom/voterandom.lua
* Fixed script error when the bans tab has never been opened and a ban is being added through the commands tab.
* Added a hook for other mods/plugins to change the position and visibility of the "All talk is enabled" text to better fit extra HUD elements.
* Added `VoteConstraints` configuration options to constrain when a vote can occur based on the current difference in average skill and optionally standard deviation of skill.
* Fixed bots showing up in `sh_teamstats`.
=> Add shuffle vote constraints, fix minor issues

locale/shine/extensions/afkkick/enGB.json, lua/shine/core/server/commands.lua, lua/shine/core/server/config.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/afkkick/shared.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/lib/objects/rate_limiter.lua, test/extensions/voterandom/voterandom.lua, test/lib/objects/rate_limiter.lua
* Improved the message displayed when a player is warned and the server has less than `MinPlayers` connected. It will now inform them that they will be kicked only if they exceed `KickTime` and the number of players reaches `MinPlayers`.
* The plugin now overrides the vanilla AFK timer to ensure infantry portals know when players are AFK.
* Team statistics for `sh_teamstats` and vote constraints are now cached to improve performance in certain cases.
* Added a rate limit to command execution. This can be changed with the `MaxCommandsPerSecond` option in the base config.
=> Apply rate limits to commands, update AFK kick

lua/shine/extensions/afkkick/server.lua
* Any activity now immediately prevents a player from being eligible for kicking when using `KickOnConnect` when using strict mode, rather than requiring activity relative to the time AFK.
* Fixed a rare script error when attempting to move players into spectate/ready room.
=> Improve AFK kick behaviour when using KickOnConnect

lua/shine/core/server/commands.lua, lua/shine/extensions/adverts/server.lua, lua/shine/lib/string.lua, lua/shine/lib/timer.lua, test/lib/string.lua
* Advert cycles can now be [started/stopped at specific system times/dates](https://github.com/Person8880/Shine/issues/698#issuecomment-406803808) using the `SYSTEM_TIME` trigger type.
* Fixed chat commands accepting too many possible characters to be triggered. They can now only be triggered by either `!` or `/`.
=> Add system time based advert triggers, alter chat command matching

locale/shine/extensions/chatbox/enGB.json, locale/shine/extensions/mapvote/enGB.json, lua/shine/core/server/permissions.lua, lua/shine/core/shared/base_plugin.lua, lua/shine/core/shared/config.lua, lua/shine/core/shared/hook.lua, lua/shine/extensions/adverts/server.lua, lua/shine/extensions/badges.lua, lua/shine/extensions/basecommands/gamerules.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/mapvote/cycle.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/mapvote/shared.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/lib/gui/layout/units/default.lua, lua/shine/lib/gui/objects/slider.lua, test/core/server/permissions.lua, test/core/shared/config.lua, test/extensions/adverts.lua, test/extensions/badges.lua, test/extensions/basecommands.lua
* Added new advert triggers:
* `COMMANDER_LOGGED_IN`
* `MARINE_COMMANDER_LOGGED_IN`
* `ALIEN_COMMANDER_LOGGED_IN`
* `COMMANDER_LOGGED_OUT`
* `MARINE_COMMANDER_LOGGED_OUT`
* `ALIEN_COMMANDER_LOGGED_OUT`
* `COMMANDER_EJECTED`
* `MARINE_COMMANDER_EJECTED`
* `ALIEN_COMMANDER_EJECTED`
* Each of the new triggers may be formatted with the commander's name using `{CommanderName}`.
* Badges can [now be forced](https://github.com/Person8880/Shine/wiki/Badges#forcing-badges) by adding a `ForcedBadges` entry to either a user or group.
* Eject votes [can now have different percentages](https://github.com/Person8880/Shine/issues/709#issuecomment-414123447) of the team required depending on how long a commander has commanded in the current round.
* Added an option to make the outer chat follow the …
=> Forced badges, vote permissions, commander adverts, eject vote customisation and fixes

locale/shine/extensions/afkkick/enGB.json, lua/shine/core/server/permissions.lua, lua/shine/core/shared/config.lua, lua/shine/core/shared/hook.lua, lua/shine/extensions/adverts/advert_stream.lua, lua/shine/extensions/adverts/server.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/afkkick/shared.lua, lua/shine/extensions/badges.lua, lua/shine/extensions/ban/server.lua, lua/shine/extensions/basecommands/rates.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/commbans/server.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/extensions/voterandom/team_optimiser.lua, lua/shine/lib/objects/votes.lua, test/core/server/permissions.lua, test/extensions/adverts.lua
* Triggered adverts can now specify a game state filter.
* Altered the format of the warning message when enough players are present to kick and `KickOnConnect` is not enabled to no longer use the vanilla AFK message.
* Fixed rate settings not applying correctly on the high rate alpha build and for any future changes to default rates, and moved them to their own `Rates` section of the config.
* Added `Rates.ApplyRates` option to control whether rate values in the config should be applied or not. Set this to `false` to always use the default rates.
* Altered the hook used to apply bans to avoid potential issues.
* Added extra debug logging.
* Updated `sh_teamstats` to indicate when the shuffling algorithm has been modified, and to show the number of players that got their preferred team in …
=> Various bug fixes and improvements

locale/shine/extensions/voterandom/enGB.json, lua/shine/core/client/votemenu_gui.lua, lua/shine/core/server/logging.lua, lua/shine/core/server/permissions.lua, lua/shine/core/shared/config.lua, lua/shine/core/shared/hook.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/extensions/voterandom/team_optimiser.lua, lua/shine/lib/class.lua, lua/shine/lib/gui.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/objects/colour_label.lua, lua/shine/lib/gui/objects/label.lua, lua/shine/lib/gui/objects/shadow_label.lua, lua/shine/lib/gui/objects/tooltip.lua, lua/shine/lib/player.lua, test/extensions/voterandom/team_optimiser.lua
* Added `sh_listgags` command to print all gagged players to the console.
* Team preference can now be accounted for during team optimisation. Set the `TeamPreferences.CostWeighting` to one of `LOW`, `MEDIUM` or `HIGH` to control how strongly to consider team preference. Higher values may result in slightly more imbalanced teams, but should better respect team preferences.
* Improved behaviour when team preference weighting is `NONE` to no longer ignore potential swaps when players have a team preference but are not on the team they want.
* Team preferences are now automatically set whenever a player intentionally joins a team using either console commands or walking through a team door.
* This is set even if they cannot yet join the given team.
* This preference is reset at the end of a …
=> Improve team preference handling in shuffle

lua/shine/cl_init.lua, lua/shine/core/shared/extensions.lua, lua/shine/core/shared/hook.lua, lua/shine/core/shared/logging.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/commbans/shared.lua, lua/shine/extensions/logging.lua, lua/shine/extensions/pregame/shared.lua, lua/shine/extensions/tournamentmode/shared.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/workshopupdater/server.lua, lua/shine/init.lua, lua/shine/lib/gui.lua, lua/shine/startup.lua
* Players that have never moved since loading in will now be treated as AFK and not placed on a team, regardless of how long they have been idle.
* Removed old NS2:Combat compatibility layer.
=> Remove NS2:Combat compatibility layer, update AFK logic in shuffle

locale/shine/extensions/basecommands/enGB.json, locale/shine/extensions/voterandom/enGB.json, lua/shine/core/server/permissions.lua, lua/shine/core/shared/config.lua, lua/shine/core/shared/hook.lua, lua/shine/core/shared/hotfix.lua, lua/shine/extensions/adverts/server.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/ban/server.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/basecommands/shared.lua, lua/shine/extensions/chatbox/chatline.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/pingtracker/server.lua, lua/shine/extensions/pregame/server.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/lib/gui/objects/panel.lua, lua/shine/lib/gui/objects/scrollbar.lua, test/core/server/permissions.lua, test/core/shared/config.lua, test/core/shared/hook.lua, test/extensions/ban.lua
* Fixed a script error that could occur when a vanilla ban entry has a non-number `time` value.
* `sh_changelevel` (`!map`) now accepts map names without the `ns2_` prefix, as well as partial map names. It will first attempt to find an exact matching map, then add `ns2_` to the start, and finally search all known maps for exactly one that contains the given map name. If a map is unknown (i.e. not in the map cycle or mounted as a `.level` file), it will no longer attempt to load it blindly and instead display an error message.
* Fixed an empty space being left at the bottom of the chatbox sometimes after many messages have been received.
* The default start delay time is now 30 seconds.
* Updated the [configuration format](https://github.com/Person8880/Shine/wiki/Pregame#config) to be more …
=> Numerous bug fixes, improve sh_changelevel, update pregame config

lua/shine/core/shared/hook.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/welcomemessages/server.lua
* Fixed `ClientConnect` event being hooked too early after changes in the last update, which meant plugins such as AFK kick would fail to handle connection events properly.
* Prevented welcome messages plugin from handling bad calls to `Server.DIsconnectClient()`.
=> Fix ClientConnect hook order, improve OnScriptDisconnect hook

lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/chatbox/chatline.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/objects/button.lua, lua/shine/lib/objects/logger.lua, lua/shine/modules/logger.lua
* Fixed some labels (commander/rookie tags and wrapped lines) being invisible in the chatbox.
* Fixed an error being thrown when a plugin that uses a logger has an invalid `LogLevel` in its configuration file. Invalid levels are now replaced with `INFO` and a warning is logged.
* Fixed tooltips and menus not inheriting styling from their parent element.
=> Minor bug fixes in the chatbox, logger config and SGUI

lua/shine/core/server/logging.lua, lua/shine/core/shared/base_plugin/config.lua, lua/shine/core/shared/misc.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/ban/client.lua, lua/shine/init.lua, lua/shine/lib/gui.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/objects/button.lua, lua/shine/lib/gui/objects/label.lua, lua/shine/lib/gui/objects/textentry.lua, lua/shine/lib/gui/skins/default_light.lua
* Improved debug log output to better explain what the plugin is attempting to do when applying warning actions.
* Fixed labels at the top of the chat history sometimes being invisible until scrolled into view.
* Fixed script error that could occur when switching between the bans and commander bans tabs in quick succession.
* Fixed off-by-one error in `TextEntry` mouse to cursor translation which meant clicking near the start of a character would put the caret at the end of it.
* `Label` controls now ensure they render properly when they are beneath a cropped element.
* Sending network messages using `Shine:ApplyNetworkMessage` (e.g. through the plugin `SendNetworkMessage` method) now defaults to setting the reliable flag to `true` when omitted rather than throwing an error.
=> Improved logging, SGUI fixes, minor bug fixes

lua/shine/core/client/config.lua, lua/shine/core/client/votemenu.lua, lua/shine/extensions/basecommands/client.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/mapvote/client.lua, lua/shine/extensions/mapvote/cycle.lua, lua/shine/extensions/voterandom/client.lua
* Buttons that conflict with the vote menu binding are now listed with the action they are bound to during a map vote.
* Fixed benign error when no map can be found in the map cycle that passes the configured restrictions when cycling the map.
* Moved all talk text down below the team HUD when it's displayed at the top of the screen.
* Removed old startup console messages.
=> Minor bug fixes and improvements

lua/shine/core/server/permissions.lua, lua/shine/core/shared/config.lua, lua/shine/extensions/adverts/advert_stream.lua, lua/shine/extensions/adverts/server.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/readyroom.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/lib/player.lua, lua/shine/lib/utf8.lua, test/core/shared/config.lua, test/extensions/adverts.lua, test/extensions/afkkick.lua, test/extensions/mapvote.lua, test/extensions/voterandom/voterandom.lua, test/lib/utf8.lua
* Advert streams and individual adverts can now specify a `MinPlayers` and/or `MaxPlayers` constraint to prevent them displaying if the player count is not in bounds.
* Streams with no trigger will automatically start/stop as the player count changes.
* Streams with a trigger will stop if the player count is no longer in range, but will **not** automatically start if the player count changes to be in range. The player count conditions are evaluated when the stream's trigger fires only.
* A stream with adverts with their own player count range will skip each advert that is not valid for the current player count until one is found that is.
* Warning time, kick time and marking players AFK can now be configured based on player count using an array of intervals in the `PlayerCountRules` …
=> Add player count based configuration options, shuffle improvements

locale/shine/extensions/mapvote/enGB.json, locale/shine/extensions/votealltalk/enGB.json, locale/shine/extensions/voterandom/enGB.json, lua/shine/core/client/votemenu_gui.lua, lua/shine/core/server/votemenu.lua, lua/shine/core/shared/config.lua, lua/shine/core/shared/hook.lua, lua/shine/core/shared/votemenu.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/logging.lua, lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/objects.lua, lua/shine/lib/objects/set.lua, lua/shine/lib/player.lua, lua/shine/modules/sh_vote.lua, lua/shine/modules/vote.lua, test/core/shared/config.lua, test/extensions/afkkick.lua, test/lib/objects.lua
* Fixed players being kicked when a round is not in progress, `OnlyCheckOnStarted` is `true` and `KickOnConnect` is `true`.
* `MinPlayers` is now used when `KickOnConnect` is `true` providing it is between the number of player slots, and the number of player + spectator slots.
* Added log messages when the Alien commander starts consuming, cancels consuming, and finishes consuming buildings, controlled by the `LogConsuming` config option (defaulting to `true`).
* Added a log message when a Marine commander cancels recycling a building (controlled by the existing `LogRecycling` config option).
* Added `VoteSettings.ConsiderSpectatorsInVotes` option to control whether spectators are included in votes.
* Spectators are no longer considered part of the total player count for …
=> Improve KickOnConnect, vote options, logging and minor bug fixes

locale/shine/extensions/voterandom/enGB.json, lua/shine/core/client/votemenu_gui.lua, lua/shine/core/server/permissions.lua, lua/shine/core/shared/config.lua, lua/shine/extensions/voterandom/client.lua, lua/shine/extensions/voterandom/friend_groups.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/shared.lua, test/extensions/voterandom/voterandom.lua
* Fixed skill difference constraints preventing a shuffle when team player counts differ by 1 and there is an eligible player in the ready room that could be shuffled to make the teams even.
* Added an indication of the team preference of the friend group a player is in to make it clear when a player's own preference differs from the rest of the group.
* Pressing the escape key when the vote menu is open now only closes the vote menu and does not also open the main menu.
* Improved validation of user data.
=> Minor shuffle improvements and bug fixes

lua/shine/core/client/votemenu_gui.lua, lua/shine/extensions/basecommands/server.lua, lua/shine/extensions/mapvote/client.lua, lua/shine/extensions/mapvote/cycle.lua, lua/shine/extensions/mapvote/map_data_repository.lua, lua/shine/extensions/mapvote/ui/map_vote_menu.lua, lua/shine/extensions/mapvote/ui/map_vote_notification.lua, lua/shine/extensions/mapvote/voting.lua, lua/shine/lib/gui.lua, test/extensions/mapvote.lua
* Fixed a script error when permanently enabling a server-side only plugin that was not previously loaded.
* Improved behaviour of map preview loading to avoid texture pop-in for maps not loaded from mods.
* Improved map mod detection logic to avoid false positives in certain cases.
* Fixed a rare script error when updating the map vote notification.
=> Fix various minor issues with map vote

locale/shine/extensions/improvedchat/enGB.json, lua/shine/core/shared/base_plugin.lua, lua/shine/extensions/afkkick/server.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/improvedchat/client.lua, lua/shine/extensions/serverswitch/client.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/lib/gui/objects/tabbedpanel.lua
* Fixed players that join a team without moving their mouse or pressing movement buttons being treated as AFK.
* The hint indicating where to configure the chat now directs players to the chatbox settings menu if the chatbox is enabled.
* Fixed a rare script error when the plugin is disabled after the vote menu page has been opened.
* Fixed some minor UI layout issues.
=> Fix minor bugs and improve AFK kick activity checks

lua/shine/core/client/adminmenu.lua, lua/shine/core/client/config_gui.lua, lua/shine/core/client/system_notifications.lua, lua/shine/core/server/config.lua, lua/shine/extensions/ban/client.lua, lua/shine/extensions/basecommands/client.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/improvedchat/client.lua, lua/shine/extensions/mapvote/client.lua, lua/shine/extensions/mapvote/ui/map_vote_menu.lua, lua/shine/extensions/mapvote/ui/map_vote_menu_tile.lua, lua/shine/extensions/mapvote/ui/map_vote_notification.lua, lua/shine/lib/gui/layout/units/default.lua, lua/shine/lib/gui/objects/button.lua, lua/shine/lib/gui/objects/categorypanel.lua, lua/shine/lib/gui/objects/label.lua, lua/shine/lib/gui/objects/list.lua, lua/shine/lib/gui/objects/menu.lua, lua/shine/lib/gui/objects/notification.lua, lua/shine/lib/gui/objects/tabbedpanel.lua
* Fixed the base config being saved unnecessarily after every map change.
* Optimised use of repeated constant layout units in SGUI.
* Constant values for 100%, 75%, 50%, 25% and auto-size units are now provided to avoid creating unnecessary duplicates and to optimise out redundant checks.
=> Fix unnecessary base config saving, minor SGUI optimisations

lua/shine/core/client/chat.lua, lua/shine/core/shared/hook.lua, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/improvedchat/client.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/lib/debug.lua, lua/shine/lib/gui/objects/textentry.lua, lua/shine/lib/gui/richtext/elements/spacer.lua, test/extensions/mapvote.lua, test/extensions/voterandom/voterandom.lua, test/lib/debug.lua
* Improved detection of certain commander actions such as dropping medpacks.
* Fixed the chat position not being reset correctly when disabling the "move outer messages" option in the chatbox.
* Added support for team and commander skill values which are enabled by default. Use the `BalanceModeConfig.HIVE` section of the plugin config to enable/disable them. Note that these will only work with the upcoming build 335 game update. See the [plugin's wiki page](https://github.com/Person8880/Shine/wiki/Vote-Random#teamrole-based-skills) for details on how these new values are used.
* Applied various compatibility fixes for changes to the chat in the upcoming build 335 game update.
=> Add team/commander skill support to shuffle, fix build 335 issues

locale/shine/extensions/voterandom/enGB.json, lua/shine/extensions/chatbox/client.lua, lua/shine/extensions/mapvote/client.lua, lua/shine/extensions/pregame/server.lua, lua/shine/extensions/voterandom/client.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/objects/tabbedpanel.lua, lua/shine/lib/gui/objects/tooltip.lua, lua/shine/lib/gui/skins/default.lua, lua/shine/lib/gui/skins/default_light.lua
* Fixed the vote menu button not displaying the number of votes cast to start a map vote.
* Added a new `AutoAddCommanderBots` option (default `true`) that will add commander bots when starting a game for any team without a commander.
* Commander bots are no longer removed by a shuffle when `ApplyToBots` is `false`.
* The `sh_teamstats` command will now indicate whether team/commander skills are being used or not.
=> Improve default shuffle and pregame behaviour

lua/shine/extensions/ban/server.lua, lua/shine/extensions/voterandom/friend_groups.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/lib/player.lua, lua/shine/lib/timer.lua, test/extensions/voterandom/voterandom.lua, test/lib/timer.lua
* Fixed family sharing queries being fired for bots.
* Friend groups are now saved across map changes and will be restored for up to 5 minutes after a map change by default (controlled by the `TeamPreferences.FriendGroupRestoreTimeoutSeconds` option).
* Fixed team optimisation using incorrect skill values if external plugins altered the teams to have more than a 1 player size difference before a shuffle.
=> Restore friend groups on map change, minor bug fixes

lua/shine/extensions/mapvote/server.lua, lua/shine/extensions/votealltalk/server.lua, lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/votesurrender/server.lua, lua/shine/modules/vote.lua, test/test_init.lua
* Added the `VoteSettings.ConsiderSpectatorsDuringActiveRound` option. When `false`, spectators cannot vote during an active round. Note that the existing `VoteSettings.ConsiderSpectatorsInVotes` option must still be `true` for spectators to be able to vote.
* Added the `VoteSettings.ConsiderSpectatorsDuringActiveRound` option.
* Added the `VoteSettings.ConsiderSpectatorsDuringActiveRound` option.
* Fixed errors related to logging when loading the plugin.
=> Add option to limit specator votes in active round, bug fixes

lua/shine/core/server/logging.lua, lua/shine/extensions/afkkick/server.lua
* Fixed players that join a team during the round start countdown being ignored until moved to the ready room/spectators.
* Added the `sh_afk_status` command which prints a summary of the AFK state of a player or all players to the console.
=> Fix AFK kick using old frozen flags

lua/shine/extensions/voterandom/server.lua, lua/shine/extensions/voterandom/team_balance.lua, test/extensions/voterandom/team_balance.lua
* Added the `BalanceModeConfig.HIVE.BlendAlienCommanderAndFieldSkills` option. When enabled, shuffle will use the average of an alien commander's field and commander skill, instead of just their commander skill. This may improve results for commanders that frequently leave the hive to fight.
=> Add blending option for alien commander skill

lua/shine/extensions/ban/server.lua, lua/shine/extensions/voterandom/team_balance.lua, lua/shine/lib/player.lua, test/extensions/ban.lua
* Added the `sh_ban_family_share_immune` permission, which can be used to make certain users immune to family sharing checks.
* Fixed a rare script error with the `sh_forcerandom` command.
=> Add family sharing check immunity and fix minor bug

lua/shine/core/server/permissions.lua, lua/shine/extensions/badges.lua, lua/shine/lib/query.lua, lua/shine/lib/table.lua, test/extensions/badges.lua, test/lib/gui/richtext/elements/text.lua, test/lib/table.lua, test/test_init.lua
* Named badge lists can now be defined once in the `Badges` section of the user config and then re-used elsewhere in the file. This avoids needing to repeat the same badge list multiple times. See [the wiki for details](https://github.com/Person8880/Shine/wiki/Badges#named-badge-lists).
* Reduced performance impact when handling a large number of badges across multiple columns for users where user data is not reloaded after startup.
* User data is no longer reloaded and saved when user data loaded remotely does not differ from the locally cached data.
=> Improve badge config and remote user loading

lua/shine/extensions/motd.lua, lua/shine/extensions/voterandom/friend_groups.lua, lua/shine/extensions/welcomemessages/server.lua, lua/shine/lib/player.lua, lua/shine/modules/player_memory.lua, test/extensions/voterandom/voterandom.lua
* Fixed script errors if friend groups contained bots on the previous map and those groups attempt to restore themselves.
* Generic welcome messages are no longer repeated every map change, only players that have not previously connected will be displayed.
=> Fix friend group errors, improve welcome message tracking

lua/shine/core/server/permissions.lua, lua/shine/extensions/badges.lua, lua/shine/extensions/namefilter.lua, lua/shine/extensions/pregame/server.lua, lua/shine/extensions/voterandom/server.lua, test/extensions/namefilter.lua, test/extensions/voterandom/voterandom.lua, test/test_init.lua
* Improved resiliency to changes in loading order when assigning names to badges.
* Improved the `RENAME` filter action to avoid duplicate names.
* The `MaxPlayers` option now applies to the number of players on the server that are not in spectate, rather than the number of players on playing teams.
* Fixed bots sometimes preventing human players from being assigned to teams when `ApplyToBots` is `true`.
=> Improve shuffle bot handling and pregame max player count

lua/shine/core/shared/hook.lua, lua/shine/lib/debug.lua, lua/shine/lib/table.lua
New lua sandbox of the upcoming ns2 build 343 does not allow access to debug.getmetatable and C-functions anymore.
The new ns2 build is available for testing at the steam beta branch.
=> tweak: Fix debug lib usage for build 343

lua/shine/extensions/ban/server.lua, lua/shine/extensions/voterandom/team_balance.lua, test/extensions/voterandom/voterandom.lua
* Fixed error when converting NS2 ban format from remote ban data.
* Fixed historic team preferences not being recorded as expected, resulting in team preferences not being weighted properly.
=> Fix shuffle team preference history and fix ban data conversion

locale/shine/core/enGB.json, locale/shine/extensions/tweaks/enGB.json, lua/shine/core/client/config_gui.lua, lua/shine/core/shared/base_plugin/config.lua, lua/shine/core/shared/commands.lua, lua/shine/core/shared/extensions.lua, lua/shine/extensions/tweaks/client.lua, lua/shine/extensions/tweaks/minimap_blend_view.lua, lua/shine/extensions/tweaks/minimap_view.lua, lua/shine/lib/gui.lua, lua/shine/lib/gui/base_control.lua, lua/shine/lib/gui/layout/units/default.lua, lua/shine/lib/gui/mixins/auto_sizable_text.lua, lua/shine/lib/gui/objects/colour_picker.lua, lua/shine/lib/gui/objects/slider.lua, lua/shine/lib/gui/skins/default.lua, lua/shine/lib/gui/skins/default_light.lua, lua/shine/lib/gui/util/pipeline.lua
This is an old branch I've had lying around for years. It implements fully automatic location highlighting on the main minimap for marines and aliens that works on any map.
It uses the location entities to determine how to highlight the current location, which for the most part creates a reasonable result (barring a few places where triggers weren't quite lined up with the playable space, though in such cases it's a useful debug tool for mappers (admittedly it's a bit late for that now though)).
=> Add tweaks plugin that adds minimap location highlighting

lua/shine/cl_init.lua, lua/shine/core/shared/base_plugin/adminmenu.lua, lua/shine/core/shared/base_plugin/commands.lua, lua/shine/core/shared/base_plugin/config.lua, lua/shine/core/shared/base_plugin/messaging.lua, lua/shine/core/shared/base_plugin/networking.lua, lua/shine/core/shared/base_plugin/timers.lua, lua/shine/core/shared/config.lua, lua/shine/core/shared/extensions.lua, lua/shine/core/shared/hook.lua, lua/shine/core/shared/logging.lua, lua/shine/core/shared/misc.lua, lua/shine/extensions/pregame/predict.lua, lua/shine/extensions/pregame/server.lua, lua/shine/extensions/pregame/shared.lua, lua/shine/lib/datatables.lua, lua/shine/lib/objects/logger.lua, lua/shine/predict_init.lua, lua/shine/startup.lua, test/lib/objects/logger.lua
These changes fix #704 by enabling plugins to run within the prediction VM in a limited manner, receiving data table updates from the server which can be used to drive predicted logic.
Note the following limitations:
- Network messages don't get received by the prediction VM despite it having a function to hook them. Thus only data table variables can be used for networking.
- Only plugins that have a `predict.lua` file will be loaded in the prediction VM.
- No `Think` hook exists in the prediction VM (as it has no update event), use `OnProcessMove` instead.
=> Fix pregame attack prediction

locale/shine/extensions/improvedchat/enGB.json, lua/shine/core/shared/base_plugin/networking.lua, lua/shine/core/shared/extensions.lua, lua/shine/core/shared/hook.lua, lua/shine/core/shared/misc.lua, lua/shine/extensions/improvedchat/client.lua, lua/shine/lib/datatables.lua, lua/shine/lib/debug.lua, lua/shine/lib/gui/font_manager.lua, lua/shine/lib/query.lua, lua/shine/predict_init.lua
* Added an option to control whether a sound is played when a chat message is displayed.
* Improved type checking in HTTP request functions.
* Fixed race condition that could cause `Shine.TimedHTTPRequest` to invoke both the response and timeout callbacks.
* The `OnFailure` callback for `Shine.HTTPRequestWithRetry` is now optional.
* Server population query functions now de-duplicate requests when cached data is unavailable and catch errors when invoking a callback with a cached failure response.
* Fixed error stack traces being cut off early due to overly sensitive stack overflow detection.
* Fixed corrupt/invalid font files causing errors at startup when pre-calculating font sizes.
* Fixed issues with predict VM logging and removed all network message interactions (these changes have …
=> Fix a few minor bugs, add option to mute chat sounds
